name: Auto Scraper

on:
  schedule:
    # Run every 5 mins from 14:30 IST to 17:25 IST (9:00 UTC to 11:55 UTC)
    - cron: '*/5 9-11 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run Scraper
        env:
          LOTTERY_URL: ${{ vars.LOTTERY_URL }}
        run: python scraper.py
